version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.4.0

jobs:
  setup:

    executor: continuation/default

    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export DEPLOY_WORKFLOW="false"' >> "$BASH_ENV"
      - continuation/continue:
          parameters: '{ "deploy_workflow": ${DEPLOY_WORKFLOW} }'
          configuration_path: .circleci/config_main.yml

workflows:
  setup-workflow:
    jobs:
      - setup