version: 2.1

parameters:
  branch:
    type: string
    default: << pipeline.git.branch >>

commands:
  provision-k8s:
    parameters:
      branch:
        type: string
    steps:
      - run:
          name: Echo the passed parameter
          command: echo << parameters.branch >>

jobs:
  prep_k8s:
    docker:
      - image: cimg/node:14.4
    parameters: # parameters are at the job level
      branch:
        type: string
    steps:
      - provision-k8s:
          branch: << parameters.branch >> # you can pass down the parameter value to the step

workflows:

  deploy_k8s_workflow:
    jobs:
      - prep_k8s:
          branch: << pipeline.parameters.branch >>