version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.4.0

jobs:

  setup:
    description: |
      This setup job is used to dynamicaly generate pipeline parameters passed to config_main.yml
      All types of actions should exist as parameters and env_vars of the same name should be populated in the job's steps
      These actions are extracted from git commit message and scheduled pipelines

    parameters:
      deploy_workflow:
        type: env_var_name
        default: DEPLOY_WORKFLOW

    executor: continuation/default

    steps:
      - checkout
      - run:
          name: Set env variables
          description: This step is extracting strings from git commit message thus deciding which workflow should be run in config_main.yml
          command: |
              echo "export DEPLOY_WORKFLOW=true" >> $BASH_ENV
      - run: 
          name: Create JSON parameter file
          command: |
            jq -n \
                --argjson deploy_workflow ${<< parameters.deploy_workflow >>} \
                '
                {
                  "deploy_workflow": $deploy_workflow
                }
                ' \
            >> .circleci/parameters.json
      - continuation/continue:
          parameters: .circleci/parameters.json
          configuration_path: .circleci/config_main.yml

workflows:
  setup-workflow:
    jobs:
      - setup