version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.4.0

jobs:
  setup:

    parameters:
      deploy_workflow:
        type: env_var_name
        default: DEPLOY_WORKFLOW

    executor: continuation/default

    steps:
      - checkout
      - run:
          name: Set env variable DEPLOY_WORKFLOW
          command: |
              echo "export DEPLOY_WORKFLOW=false" >> $BASH_ENV
      - run: 
          name: Create JSON parameter file
          command: |
            echo "{ \"deploy_workflow\": ${<< parameters.deploy_workflow >>} }" >> parameters.json
            cat parameters.json
      - continuation/continue:
          parameters: parameters.json
          configuration_path: .circleci/config_main.yml

workflows:
  setup-workflow:
    jobs:
      - setup