version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.4.0

jobs:

  setup:
    description: |
      This setup job is used to dynamicaly generate pipeline parameters passed to config_main.yml
      These actions are extracted from git commit message and scheduled pipeline parameters

    executor: continuation/default

    steps:
      - checkout
      - run:
          name: Set env variables
          description: |
            This step is extracting strings from git commit message / scheduled pipeline parameters
            and populating env variables which in turn are used as input pipeline parameters to config_main.yml
          command: |
              echo "export DEPLOY_WORKFLOW=false" >> $BASH_ENV
      - run: 
          name: Create JSON parameter file
          description: This JSON parameter file contains all parameters passed to config_main.yml file
          command: |
            jq -n \
                --argjson deploy_workflow ${DEPLOY_WORKFLOW} \
                '
                {
                  "deploy_workflow": $deploy_workflow
                }
                ' \
            >> .circleci/parameters.json
      - continuation/continue:
          parameters: .circleci/parameters.json
          configuration_path: .circleci/config_main.yml

workflows:
  setup-workflow:
    jobs:
      - setup