version: 2.1

executors:
  deploy-executor:
    machine:
      image: ubuntu-2204:2023.04.2

commands:
  install-openvpn:
    description: "Command to install OpenVPN client on a machine executor"
    steps:
      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update
            sudo apt-get install openvpn openvpn-systemd-resolved
orbs:
  terraform: circleci/terraform@3.2.1
  helm: circleci/helm@2.0.1
  kubernetes: circleci/kubernetes@1.3.1
          
jobs:
  deploy:
    executor: deploy-executor
    steps:
      - checkout
      - helm/install-helm-client:
          version: v3.12.0
      - run:
          name: Install Helm S3 Plugin
          description: "Command to install helm s3 plugin"
          command: helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.14.0
      - run:
          name: Install Helm SSM Plugin
          description: "Command to install helm ssm plugin"
          command: helm plugin add https://github.com/codacy/helm-ssm
      - terraform/install:
          terraform_version: 1.4.6
      - kubernetes/install-kubectl:
          kubectl-version: v1.23.0
      - install-openvpn

workflows:
  deploy_workflow:
    jobs:
      - deploy:
          context:
            - circleci-test