version: 2.1

executors:
  deploy-executor:
    machine:
      image: ubuntu-2204:2023.04.2

commands:

  install-openvpn:
    description: "Commands to install OpenVPN client on a machine executor"
    steps:
      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get install openvpn openvpn-systemd-resolved
  
  connect-openvpn:
    description: "Commands to configure OpenVPN client and make a VPN connection"
    steps:
      - run:
          name: VPN Setup and Connect
          background: true
          command: |
            echo $VPN_CLIENT_CONFIG | base64 --decode > /tmp/config.ovpn

            if grep -q auth-user-pass /tmp/config.ovpn; then
              if [ -z "${VPN_USER:-}" ] || [ -z "${VPN_PASSWORD:-}" ]; then
                echo "Your VPN client is configured with a user-locked profile. Make sure to set the VPN_USER and VPN_PASSWORD environment variables"
                exit 1
              else
                printf "$VPN_USER\\n$VPN_PASSWORD" > /tmp/vpn.login
              fi
            fi

            vpn_command=(sudo openvpn
              --config /tmp/config.ovpn
              --route 169.254.0.0 255.255.0.0 net_gateway
              --script-security 2
              --up /etc/openvpn/update-systemd-resolved --up-restart
              --down /etc/openvpn/update-systemd-resolved --down-pre
              --dhcp-option DOMAIN-ROUTE .)

            if grep -q auth-user-pass /tmp/config.ovpn; then
              vpn_command+=(--auth-user-pass /tmp/vpn.login)
            fi

            ET_phone_home=$(ss -Hnto state established '( sport = :ssh )' | head -n1 | awk '{ split($4, a, ":"); print a[1] }')
            echo $ET_phone_home

            if [ -n "$ET_phone_home" ]; then
              vpn_command+=(--route $ET_phone_home 255.255.255.255 net_gateway)
            fi

            for IP in $(host runner.circleci.com | awk '{ print $4; }')
              do
                vpn_command+=(--route $IP 255.255.255.255 net_gateway)
                echo $IP
            done

            for SYS_RES_DNS in $(systemd-resolve --status | grep 'DNS Servers'|awk '{print $3}')
              do
                vpn_command+=(--route $SYS_RES_DNS 255.255.255.255 net_gateway)
                echo $SYS_RES_DNS
            done

            "${vpn_command[@]}" > /tmp/openvpn.log
orbs:
  terraform: circleci/terraform@3.2.1
  helm: circleci/helm@2.0.1
  kubernetes: circleci/kubernetes@1.3.1
          
jobs:
  deploy:
    executor: deploy-executor
    steps:
      - checkout
      - helm/install-helm-client:
          version: v3.12.0
      - run:
          name: Install Helm S3 Plugin
          description: "Command to install helm s3 plugin"
          command: helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.14.0
      - run:
          name: Install Helm SSM Plugin
          description: "Command to install helm ssm plugin"
          command: helm plugin install https://github.com/codacy/helm-ssm
      - terraform/install:
          terraform_version: 1.4.6
      - kubernetes/install-kubectl:
          kubectl-version: v1.23.0
      - install-openvpn

workflows:
  deploy_workflow:
    jobs:
      - deploy:
          context:
            - circleci-test