version: 2.1

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: echo "I am on main within when clause"
      - run: echo "I am on main outside of when clause"

workflows:
  my-workflow:
    jobs:
      - my-job