version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - helm/install-helm-client
      - terraform/install:
          terraform_version: 1.4.6

orbs:
  terraform: circleci/terraform@3.2.1
  helm: circleci/helm@2.0.1

workflows:
  build_machine:
    jobs:
      - build:
          context:
            - circleci-test