version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.4.0

jobs:
  setup:

    executor: continuation/default

    steps:
      - checkout
      - continuation/continue:
          parameters: '{}'
          configuration_path: config_main.yml
          
workflows:
  setup-workflow:
    jobs:
      - setup