version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.4.0

jobs:

  setup-job:
    description: |
      This setup job is used to dynamicaly generate pipeline parameters passed to config_main.yml
      These actions are extracted from git commit message and scheduled pipeline parameters

    executor: continuation/default

    steps:
      - checkout
      - run:
          name: Filter workflows based on git commit message
          description: |
            This step is extracting strings from git commit message / scheduled pipeline parameters
            and populating env variables which in turn are used as input pipeline parameters to config_main.yml
          command: |
            COMMIT_MSG=$(git log --format=%B -n 1 $CIRCLE_SHA1)
            ACTION_TYPE=$(echo $COMMIT_MSG | perl -ne '/^(.+?)=/ && print "$1"')

            case $ACTION_TYPE in
              deploy)
                # DEPLOY_TYPE=$(echo $COMMIT_MSG | perl -ne '/^(.+?)=(.+?):/ && print "$2"')
                # DEPLOY_PARAMS=$(echo $COMMIT_MSG | perl -ne '/^(.+?)=(.+?):(.+?)$/ && print "$3"'
                # case $DEPLOY_TYPE in
                #   true)
                #     echo "export TERRAFORM_DEPLOY_TRUE=true" >> $BASH_ENV
                #     echo "Will execute terraform_deploy_true workflow on branch << pipeline.git.branch >>"
                #     ;;
                #   service)
                #     TARGET_MODULE=module.$(echo $DEPLOY_PARAMS | sed 's/\./\.module\./g')
                #     echo "export TERRAFORM_DEPLOY_SERVICE=true" >> $BASH_ENV
                #     echo "export TERRAFORM_DEPLOY_SERVICE_TARGET=${TARGET_MODULE}" >> $BASH_ENV
                #     source $BASH_ENV
                #     perl -le 'print "Will execute terraform_deploy_service workflow with target $ENV{TERRAFORM_DEPLOY_SERVICE_TARGET} on branch << pipeline.git.branch >>" if ($ENV{TERRAFORM_DEPLOY_SERVICE} and $ENV{TERRAFORM_DEPLOY_SERVICE_TARGET})'
                #     ;;
                #   *)
                #     echo "No deploy workflow defined for message:"
                #     echo ${COMMIT_MSG}
                #     ;;
                # esac
                # ;;
                echo 'dejan'
            esac

      - run: 
          name: Create JSON parameter file
          description: This JSON parameter file contains all parameters passed to config_main.yml file
          command: |
            jq -n \
                --argjson terraform_deploy_true ${TERRAFORM_DEPLOY_TRUE:=false}  \
                --argjson terraform_deploy_service ${TERRAFORM_DEPLOY_SERVICE:=false} \
                --arg terraform_deploy_service_target ${TERRAFORM_DEPLOY_SERVICE_TARGET:=null} \
                '
                {
                  "terraform_deploy_true": $terraform_deploy_true,
                  "terraform_deploy_service": $terraform_deploy_service,
                  "terraform_deploy_service_target": $terraform_deploy_service_target
                }
                ' \
            >> .circleci/parameters.json
      - continuation/continue:
          parameters: .circleci/parameters.json
          configuration_path: .circleci/config_main.yml

workflows:
  setup-workflow:
    jobs:
      - setup-job