version: 2.1

executors:
  deploy-executor:
    docker:
      - image: cimg/aws:2023.05
     
commands:

  setup-kubernetes-client:
    description: "Commands to install kubectl client including config files for production and staging clusters"
    parameters:
      kubectl_client_version:
        type: string
        default: v1.23.0
    steps:
      - kubernetes/install-kubectl:
          kubectl-version: << parameters.kubectl_client_version >>
      - when:
          condition:
            not:
              equal: [ production, << pipeline.git.branch >> ]
          steps:
            - kubernetes/install-kubeconfig:
                kubeconfig: KUBECONFIG_STAGING
      - when:
          condition:
            equal: [ production, << pipeline.git.branch >> ]
          steps:
            - kubernetes/install-kubeconfig:
                kubeconfig: KUBECONFIG_PRODUCTION

  setup-helm-client:
    description: "Commands to install and configure helm cli client"
    parameters:
      default_helm_plugin_dir:
        type: string
        default: "/home/circleci/.local/share/helm/plugins"
      helm_ssm_version:
        type: string
        default: 3.3.0
      helm_s3_version:
        type: string
        default: 0.14.0
      helm_client_version:
        type: string
        default: v3.12.0
    steps:
      - helm/install-helm-client:
          version: << parameters.helm_client_version >>
      - run:
          name: Configure helm client
          description: "Commands to configure helm cli client by installing plugins and initializing repository"
          command: |
            helm plugin install https://github.com/hypnoglow/helm-s3.git --version << parameters.helm_s3_version >>
            mkdir -p "<< parameters.default_helm_plugin_dir >>/helm-ssm" && curl -sL "https://github.com/codacy/helm-ssm/releases/download/<< parameters.helm_ssm_version >>/helm-ssm-linux.tgz" | tar xz -C "<< parameters.default_helm_plugin_dir >>/helm-ssm" && echo "Installed plugin: ssm"
            helm repo add vatbox-helm-repo s3://vatbox-helm-repo && echo "Repository vatbox-helm-repo added"
              

orbs:
  terraform: circleci/terraform@3.2.1
  helm: circleci/helm@2.0.1
  kubernetes: circleci/kubernetes@1.3.1
          
jobs:
  deploy:
    executor: deploy-executor
    steps:
      - checkout
      - setup-kubernetes-client:
         kubectl_client_version: v1.23.0
      - setup-helm-client:
         helm_client_version: v3.12.0
         helm_s3_version: 0.14.0
         helm_ssm_version: 3.3.0
      - terraform/install:
         terraform_version: 1.4.6

workflows:
  deploy_workflow:
    jobs:
      - deploy:
          context:
            - circleci-test