version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - helm/install-helm-client:
          version: v3.12.0
      - run:
          name: Install Helm S3 Plugin
          command: helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.14.0
      - terraform/install:
          terraform_version: 1.4.6
      - kubernetes/install-kubectl:
          kubectl-version: v1.23.0
      - persist_to_workspace:
          root: /
          paths: .
  execute:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - attach_workspace:
          at: /

orbs:
  terraform: circleci/terraform@3.2.1
  helm: circleci/helm@2.0.1
  kubernetes: circleci/kubernetes@1.3.1

workflows:
  build_machine:
    jobs:
      - build:
          context:
            - circleci-test
  execute_machine:
    jobs:
      - execute